version: '4.21.1'

services:
  jira:
    image: jira-app-image:latest
    container_name: jira
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    env_file:
      - secret_data.env

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - secret_data.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  postgres-db-test:
    image: postgres:latest
    container_name: postgres-db-test
    ports:
      - "5433:5432"
    env_file:
      - secret_data.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-test:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jira